Investment strategies
sublime-finance/sublime-protocol pull request #4
Opened 2021-02-24 07:00 UTC by amy1205

Created a general interface for Invest contract
Added invest contracts for YVault, Aave and Compound protocols

2021-02-24 09:07 UTC, prateekreddy commented
Handle Ether investments as well

2021-02-24 10:01 UTC, prateekreddy requested changes

2021-02-24 11:33 UTC, amy1205 commented on contracts/interfaces/IInvest.sol
> +     * @param amount the amount of asset
amount of liquidity shares to be unlocked

2021-02-24 11:33 UTC, amy1205 commented on contracts/interfaces/IInvest.sol
> +        returns (uint256 sharesReceived, address investedTo);
Yeah right, removed.

2021-02-24 12:11 UTC, amy1205 commented on contracts/invest/InvestAave.sol
> +        require(
Right, removed it

2021-02-24 12:14 UTC, amy1205 commented on contracts/invest/InvestCompound.sol
> +        require(ICToken(cToken).redeem(amount) == 0, "Error in unwrapping");
While redeeming, it directly burns the cTokens from msg.sender address

2021-02-24 12:15 UTC, amy1205 commented on contracts/invest/InvestYVault.sol
> +        IyVault(investedTo).withdraw(amount);
It burns the tokens from wallet, hence not needed

2021-02-25 05:50 UTC, amy1205 commented on contracts/invest/InvestCompound.sol
> +    mapping(address => address) investTo;
Yes, to get the cToken contract address to invest in. I am looking for a registry but to avoid this

2021-02-25 12:40 UTC, prateekreddy commented
@amy1205 We can mark all getTokensForShares methods to view as they don't change state.

2021-02-25 13:04 UTC, prateekreddy commented
Also probably set referral code stuff to variable may be and admin can set it

2021-02-25 13:06 UTC, prateekreddy commented
The tokenshares should instead be stored against msg.sender. The current scheme is attackable because the ownership of the tokens are with user rather than pool contract.

2021-02-26 11:30 UTC, merged